
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: adaysdb
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: "mysql://root:/adaysdb"
      NODE_ENV: "development"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    command: >
      sh -c "/app/wait-for-it.sh db:3306 --timeout=120 -- 
      sh -c 'until mysql -h db -u root -p --execute=\"SELECT 1\"; do echo \"Waiting for MySQL...\"; sleep 5; done && pnpm prisma migrate deploy --schema=./prisma/schema.prisma && pnpm run dev'"

volumes:
  mysql_data: